index:
  path: /
  controller: App\Controller\DefaultController::index

# page d'accueil
home:
  path: /home
  controller: App\Controller\DefaultController::home

# blog
blog:  
  path: /blog
  controller: App\Controller\DefaultController::blog

# section pour naviguer à travers les articles
articles:
  path: /articles
  controller: App\Controller\DefaultController::articles

# section pour naviguer à travers les catégories      
categories:
  path: /categories
  controller: App\Controller\DefaultController::categories      

 