index:
     path: /index
     controller: App\Controller\BlogController::index

# page d'accueil
home:
  path: /menu
  controller: App\Controller\MenuController::index

# section pour naviguer à travers les articles
articles:
  path: /articles
  controller: App\Controller\ArticleController::index

# section pour naviguer à travers les catégories      
categories:
  path: /categories
  controller: App\Controller\CategoryController::index     

 